NAME = btc
CPP = c++
CPPFLAG = -Wall -Werror -Wextra -std=c++11
RM = rm -rf
SRC_DIR = src
OBJ_DIR = obj

all: $(NAME)

clean:
$(RM) $(OBJ_DIR)

fclean: clean
$(RM) $(NAME)

re: fclean all

.PHONY: all, clean, fclean, re